### PR TITLE
Fixes for various crashes/ruby errors

### PR DESCRIPTION
**Pull request by ghost**
Some fixes, of the works for me(TM) variety, for errors I've encountered when trying to use this.

I have only tried these on Ruby 2.4.0.

Thanks for your work on the notmuch fork! :)

### CODE REVIEW

**Comment by KF5JWC** [comment]
I don't know where to start for this error, though.
I believe it occurs when the From header is not an email address.
`From: Microsoft\n`

```
--- NameError from thread: load messages for thread-view-mode
undefined local variable or method `header' for #<Redwood::Message:0x00xxxxxxxxxxxx>
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/message.rb:298:in `raw_header'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/message.rb:111:in `parse_header'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/message.rb:252:in `load_from_source!'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_index_mode.rb:112:in `block (3 levels) in select' 
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/thread.rb:70:in `block in each'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/thread.rb:188:in `each_with_stuff'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/thread.rb:69:in `each'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_index_mode.rb:109:in `each_with_index'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_index_mode.rb:109:in `block (2 levels) in select' 
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/buffer.rb:777:in `say'
(eval):1:in `say'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_index_mode.rb:108:in `block in select' 
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup.rb:67:in `block in reporting_thread'
```

Note: `0.22.2` is not a sup release. I set it to that. I am working from the `notmuch` branch.

**Comment by ghost** [comment]
I'm now unsure that the `encoding!` patch is correct. It works, but 590bc1d49be87360143ea69e7e2f045990997577 is very close to it, and takes a different approach.

Please let me know if that requires modification.

**Comment by ghost** [comment]
NOTES TO SELF:

Other crashers.

From header is not an email address. `From: Microsoft\n`
(Don't know where to start)

```
--- NameError from thread: load messages for thread-view-mode
undefined local variable or method `header' for #<Redwood::Message:0x00xxxxxxxxxxxx>
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/message.rb:298:in `raw_header'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/message.rb:111:in `parse_header'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/message.rb:252:in `load_from_source!'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_index_mode.rb:112:in `block (3 levels) in select' 
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/thread.rb:70:in `block in each'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/thread.rb:188:in `each_with_stuff'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/thread.rb:69:in `each'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_index_mode.rb:109:in `each_with_index'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_index_mode.rb:109:in `block (2 levels) in select' 
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/buffer.rb:777:in `say'
(eval):1:in `say'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_index_mode.rb:108:in `block in select' 
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup.rb:67:in `block in reporting_thread'
```

Trying to view raw message (`V` key)
(Don't know where to start)
```
--- NameError from thread: main
undefined local variable or method `location' for #<Redwood::Message:0x0xxxxxxxxxxxxx>
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/message.rb:302:in `raw_message'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_view_mode.rb:212:in `block in show_message'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/buffer.rb:388:in `spawn_unless_exists'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/util.rb:628:in `method_missing'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_view_mode.rb:211:in `show_message'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/mode.rb:66:in `handle_input'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/buffer.rb:306:in `handle_input'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/bin/sup:236:in `<module:Redwood>'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/bin/sup:85:in `<top (required)>'
~/.gem/ruby/2.4.0/bin/sup:22:in `load'
~/.gem/ruby/2.4.0/bin/sup:22:in `<main>'
```

After (successfully) sending mail
```
--- NameError from thread: main
uninitialized constant Redwood::EditMessageMode::SentManager
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/edit_message_mode.rb:599:in `send_message'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/mode.rb:66:in `handle_input'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/buffer.rb:306:in `handle_input'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/bin/sup:236:in `<module:Redwood>'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/bin/sup:85:in `<top (required)>'
~/.gem/ruby/2.4.0/bin/sup:22:in `load'
~/.gem/ruby/2.4.0/bin/sup:22:in `<main>'
```

Searching for `from:domain.com or to:domain.com`
(Does not break if search produces no results)
```
--- RuntimeError from thread: load threads for thread-index-mode

~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/thread.rb:356:in `block in load_thread_ids'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/thread.rb:354:in `each'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/thread.rb:354:in `each_slice'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/thread.rb:354:in `load_thread_ids'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/thread.rb:348:in `load_n_threads'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_index_mode.rb:673:in `load_n_threads'
(eval):12:in `load_n_threads'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_index_mode.rb:657:in `block in load_n_threads_background'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup.rb:67:in `block in reporting_thread'
```

Note: `0.22.2` is not a sup release. I set it to that. I am using the `notmuch` branch.

**Comment by KF5JWC** [comment]
Another crasher when trying to view raw message (`V` key)
```
--- NameError from thread: main
undefined local variable or method `location' for #<Redwood::Message:0x0xxxxxxxxxxxxx>
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/message.rb:302:in `raw_message'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_view_mode.rb:212:in `block in show_message'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/buffer.rb:388:in `spawn_unless_exists'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/util.rb:628:in `method_missing'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/modes/thread_view_mode.rb:211:in `show_message'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/mode.rb:66:in `handle_input'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/lib/sup/buffer.rb:306:in `handle_input'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/bin/sup:236:in `<module:Redwood>'
~/.gem/ruby/2.4.0/gems/sup-0.22.2/bin/sup:85:in `<top (required)>'
~/.gem/ruby/2.4.0/bin/sup:22:in `load'
~/.gem/ruby/2.4.0/bin/sup:22:in `<main>'
```

Note: `0.22.2` is not a sup release. I set it to that. I am using the `notmuch` branch.

**Pull request closed without merging**
